# The following defines the domain and requestUrl for your application
# These items will be packaged into your application for different environment
# Recommended to specify your application configrations for production or development
# Nitification for cases:
# Build configrations works on debug and release mode

# 开发环境下加载的信息
# Parameters for development mode
development:
  # 
  # Before your modification, you should know about these recommend rules:
  # CHOOSE A HTTPS SERVER
  # YOUR DOMAIN SHOULD NEVER RETURN 302 || 301 STATUS CODE
  # 
  # You are not gonna get a health application when you add a domain like https://google.com redirected into https://www.google.com
  #
  # YOUR DOMAIN SHOULD NEVER ENDED WITH PATH SEPARATOR LIKE : https://www.example.com/
  domain: https://discuz.chat
  appname: DiscuzQ
  # Allow to show checked mode banner
  debugShowCheckedModeBanner: true
  # Allow and show performance overlay setting
  enablePerformanceOverlay: true
  # HTTP2
  # PLEASE DO NOT SET THIS ITEM INTO TRUE
  # Cause Flutter Http2 contains many problems
  # We would tell you when this feature is possible for production on readme doc
  enableHttp2: false
  # Certificate
  # Verify certificate is an optional handler for unverifiable certificates, set TRUE continue to request for bad certificates.
  # works for HTTP1.0 and HTTP2
  onBadCertificate: true 
  # idleTimeout
  # default is 15000ms
  # works on HTTP2 request only
  http2idleTimeout: 15000
  #
  # Financial fatures
  # Set this item into FALSE, wallet and financial amount will be displayed
  financial: true 
  # Umeng.com analysis for mobiles
  # Get your account and appKey by clicking https://mobile.umeng.com/
  # If you do not need these functionalities just give a empty value
  #
  # Appkey for Android devices
  # For development environment empty value is recommended
  # Not work for web
  umengAndroidAppkey: 
  # Appkey for Apple IOS devices
  # For development environment empty value is recommended
  umengIOSAppkey:
  # umeng channel
  # 即 渠道分发
  umengChannel: channel
  # reportCrash
  # bool
  umengReportCrash: true
  # logEnable
  # bool
  umengLogEnable: true
  # umeng encrypt
  # bool
  umengEncrypt: true
  # Tuxiaochao
  # Get your account https://txc.qq.com/
  tuxiaochao: https://support.qq.com/embed/phone/152424
  # Sentry
  sentry: https://e60cedb74f404ff3a2bd4a0ff364d8f0@o426897.ingest.sentry.io/5371662

  
# 构建生产环境的APP时加载的信息
# Parameters for building prodution package
production:
  domain: https://discuz.chat
  appname: DiscuzQ
  ## DO NOT ENABLE THIS ITEM WHEN YOU ARE BUILD AN APPLICATION FOR YOUR USERS
  enablePerformanceOverlay: false
  ## DO NOT ENABLE THIS ITEM WHEN YOU ARE BUILD AN APPLICATION FOR YOUR USERS
  debugShowCheckedModeBanner: false
  # HTTP2
  enableHttp2: false
  onBadCertificate: true 
  http2idleTimeout: 15000
  financial: false 
  # Appkey for Android devices
  umengAndroidAppkey: 5eb7ab6f895cca574f00009e
  # Appkey for Apple IOS devices
  umengIOSAppkey: 5eb7ab8f895cca4be10000eb
  umengChannel: channel
  umengReportCrash: true
  umengLogEnable: true
  umengEncrypt: true
  tuxiaochao: https://support.qq.com/embed/phone/152424
  sentry: https://e60cedb74f404ff3a2bd4a0ff364d8f0@o426897.ingest.sentry.io/5371662

